### ISSUE TITLE
Logged in Subscriber redirects to non-existent post after successful submission of a post as a logged-in user

### ISSUE THREAD

**Issue by mayeenulislam** [weDevsOfficial/wp-user-frontend#1153]
# Steps to reproduce

1. The author is a 'Subscriber' and logged in
2. The author is trying to submit a new post
3. The default post status (after new submission) is set to 'pending' (**Post Forms &raquo; [myform] &raquo; Settings &raquo; Post Settings**, "Post Status" is "Pending Review")
3. After successful submission the plugin is trying to redirect to the blog post, but as it's pending, that's reaching a 404

# What to expect

## Easy way
Redirect everybody to the 'Write Blog' page with just a success message, and let them get onto the post from their dashboard &raquo; posts' list.

## Advanced way
Keep track of the 'status' (`wpuf_settings[post_status]`), if it's 'publish', then redirect to the blog post, otherwise keep them on the same page with just a success message.

**Comment by mmarj** [comment]
Hello @mayeenulislam Bhai,
Thanks for reach out.

As you know, it's logical and valid to have a "404" page if you set the status to "[pending review" and Redirect To " newly created post.](https://prnt.sc/1fctrjp)" Because you have set the post status as **pending review** so it can't let the users access the submitted post until it reviews by the admin/editor. In this case, you can [set a page redirection](https://prnt.sc/1fcv3z0) (_instead of " newly created post"_) with your expected message like "Thank you! your post is submitted for review it will get published soon, etc.." so that the user can redirect to that page after submitting the posting form.
