### ISSUE TITLE
Youtube not auto embedding after post.

### ISSUE THREAD

**Issue by thesunnymachine** [weDevsOfficial/wp-user-frontend#1173]
Previously you could paste a youtube link and it would auto embed the video. 

I am not sure when this broke, but now it will only post the text of the link and it doesn't automatically create the embed.

**Comment by zamandevs** [comment]
@thesunnymachine Please check on the latest version. things should work as expected.

**Comment by thesunnymachine** [comment]
> @thesunnymachine Please check on the latest version. things should work as expected.

Issue still persist. 

I can get the video to auto embed ONLY when I paste the Youtube URL alone and no other content. 

The video will not auto embed if I paste the video link and add more text any amount of lines down.  The post just shows the URL once published instead of showing the embed.  I then have to open the post in Visual Composer editor or Gutenberg, then the video will switch to the embedded version and I can republish the post.  

The problem here is that my users on my site cannot do this, only admins can do this... so when users try to post a video it still does not auto embed.

**Comment by thesunnymachine** [comment]
This issue should not be closed,.. it's still present.  I thought it was fixed because I tested with a single url, if I add extra content it is still broken.

**Comment by sapayth** [comment]
Hello @thesunnymachine,
Thank you for pointing that out. But sadly when I checked youtube link in my post content, it is working fine. I tried putting the youtube link in between other texts, and it works. Can you please share a screenshot, better yet a recording of the total process in your settings so that we can debug the problem further.

**Comment by thesunnymachine** [comment]
> Hello @thesunnymachine, Thank you for pointing that out. But sadly when I checked youtube link in my post content, it is working fine. I tried putting the youtube link in between other texts, and it works. Can you please share a screenshot, better yet a recording of the total process in your settings so that we can debug the problem further?

[https://www.youtube.com/watch?v=5n-mTYqoEY8
](https://www.youtube.com/watch?v=5n-mTYqoEY8
)
In this video, you can see the issue clearly.  I create a post with ONLY youtube URL and the embed works.  Then I create a post with the exact same URL and add some extra text to the post and it doesn't embed.

**Comment by sapayth** [comment]
It seems there has been a conflict on your site. So, this will need to check if that is coming from any theme or plugin. Please follow the below procedures for testing purposes:

1. Switched to any default theme like Twenty Twenty-One.
2. Clear your site cache as well as the browser cache and try the process again.
3. If the above method doesn't resolve your problem, then go for the next.
4. Please deactivate all plugins except WP User Frontend and WP User Frontend Pro.

**Next Step:**
If the problem still occurs please [contact our support here](https://wedevs.com/contact) so that we can take a closer look at your site with your credentials.

**Comment by thesunnymachine** [comment]
I think I found the issue. 

When I am formatting the post.  If I hold SHIFT and hit Enter twice to make the extra content, it will not embed.

If I just hit enter twice and enter the extra content, it will embed just fine.

**Comment by sapayth** [comment]
Hello @thesunnymachine,
Good to hear you have found the issue. This is the default behavior of WordPress.
