### ISSUE TITLE
Firefox does not show "Add Fields" or "Field Options" choices on editing forms

### ISSUE THREAD

**Issue by sithaandra** [weDevsOfficial/wp-user-frontend#1224]
Hi!
I am trying to Edit Posts in Wordpress (5.8.2)  in Firefox (v95.02) on my Mac (10.15.7) and I cannot see the fields when I edit  forms. The same page will show the field sections when I use Safari.  I have turned off all extensions on Firefox, but other than that I'm not sure else what I can try? Thanks for your help!

Firefox:
![Screen Shot 2022-01-05 at 12 51 42 PM](https://user-images.githubusercontent.com/79176246/148288259-5c02b9b7-c4c7-4b1e-a05d-dfedd895ae12.png)
 Safari:
![Screen Shot 2022-01-05 at 12 56 50 PM](https://user-images.githubusercontent.com/79176246/148288539-800abe8f-10b0-4a85-b128-0cdc21a85972.png)

Courtney

**Comment by sapayth** [comment]
Hello @sithaandra,
Thanks for the detailed description. Sorry to hear about your problem. As we checked, it seems working on our end. There might be a conflict with another plugin or theme. Let's do a conflict test to be confirmed.
1. Please deactivate all plugins except the WP User Frontend and WP User Frontend Pro.
2. Use a default theme such as twenty-twenty.
3. Clear your site cache as well as the browser cache. Then try again.

If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.

**Comment by sapayth** [comment]
I hope your problem is fixed. I am closing the issue for now. Feel free to open a new issue or communicate our [Support](https://wedevs.com/contact) if there is any query.
