### ISSUE TITLE
Multistep validation not working for: Website URL, Email, and Email address fields

### ISSUE THREAD

**Issue by kathybullet** [weDevsOfficial/wp-user-frontend#1237]
Validation errors for invalid email addresses or invalid URLs aren't working as you move through multi-step registration forms. The (correct format) validation isn't working across any of the following fields:

- Website URL
- E-Mail (WP user email)
- Email address

It means users CAN move through the steps (even when there is an error on the step). But the final form submit is then blocked by the (invisible) field format errors. For users it would be almost impossible to work out where the error is and why it's not working. 

See this working example (site in development): http://cde.bulletserve.net/dev-multi-step-form-test/
Enter "google" instead of "https://www.google.com" in any/all of the URL fields as an example. (I'm running WP 5.9 and the latest versions of WPUF Pro.)

Thanks

**Comment by sapayth** [comment]
Hello @kathybullet,
Sorry for the inconvenience. In `wp-content/plugins/wp-user-frontend/assets/js/frontend-form.js` please add below code at `line no: 514`:

```
/* ======== Validation ======== */
var visibleFields = self.find('input[type="url"]:visible, input[type="email"]:visible');

visibleFields.each(function(i, item) {
    var input_type = $(item).attr('type');
    var val = '';

    switch (input_type) {
        case 'url':
            val = $.trim( $(item).val() );

            if ( val !== '' ) {
                if( ! WP_User_Frontend.isValidURL( val ) ) {
                    error = true;
                    error_type = 'validation';

                    WP_User_Frontend.markError( item,  error_type );
                }
            }
            break;

        case 'email':
            val = $(item).val();

            if ( val !== '' ) {
                if( ! WP_User_Frontend.isValidEmail( val ) ) {
                    error = true;
                    error_type = 'validation';

                    WP_User_Frontend.markError( item,  error_type );
                }
            }
            break;
    }
});
```

I hope this solves your problem. Feel free to notify us of any queries or help you need.

**Comment by kathybullet** [comment]
Many thanks. That's 90% working. But I'm still getting a glitch when a user enters "www.somewhere.com".

The form let's you progress to the next step without activating a validation error. BUT the final form submit is blocked by this (non-http...) URL.

**Comment by sapayth** [comment]
That is because some browser don't treat website name that starts with www .
For now please follow below steps:

1. on `wp-content/plugins/wp-user-frontend/includes/class-frontend-render-form.php` please replace `line no:336` with below code:

    `<form class="wpuf-form-add wpuf-form-<?php echo esc_attr( $layout ); ?> <?php echo ( $layout == 'layout1' ) ? esc_html( $theme_css ) : 'wpuf-style'; ?>" action="" method="post" novalidate>`

2. On `wp-content/plugins/wp-user-frontend/assets/js/frontend-form.js` please replace `line no: 817` with below code:
`var urlregex = new RegExp("^(www\\.|http:\\/\\/www\\.|https:\\/\\/www\\.|http:\\/\\/|https:\\/\\/)?[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,20}(:[0-9]{1,20})?(\\/.*)?$");`

Feel free to let us know if this solves your problem or you encounter any problem following those steps.

**Comment by sapayth** [comment]
That is because browser don't treat website name that starts with www . And that is logical.
For now please follow below steps:

1. In `wp-content/plugins/wp-user-frontend/assets/js/frontend-form.js` please replace `line no: 817` with `var urlregex = new RegExp("^(http:\\/\\/www\\.|https:\\/\\/www\\.|http:\\/\\/|https:\\/\\/){1}[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,20}(:[0-9]{1,20})?(\\/.*)?$");`

Feel free to let us know if this solves your problem or you encounter any problem following those steps.

**Comment by kathybullet** [comment]
Many thanks, this last fix works great
