### ISSUE TITLE
[Enhancement] Auto expand Textarea field's height (box size) based on the content

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1243]
**Description:**
Currently, if you use the "post content" or "textarea" field and write a long thread, you will see it won't expand the inside box (height) of the field based on the screen view. Hence, you won't see all the texts at a glance. You need to scroll up to see your off-screen texts.
Video- https://screencast-o-matic.com/watch/c3noDqVbllj.

**Expected behavior:**
Can we have improved this behavior of the TinyMCE editor [like this](https://jsfiddle.net/uezo5cky/) or as like our [registration form's notification email editor](https://prnt.sc/26weoy3)?

**Comment by anik-fahmid** [comment]
**Expected behavior:** Text-box expands in height with text

![image](https://user-images.githubusercontent.com/18075711/219574124-4388f2d1-8491-4d11-ac30-c09110646fb2.png)

Current behavior: Doesn't expand, shows scrolling bar on right 

![image](https://user-images.githubusercontent.com/18075711/219574661-009bf84a-61ce-49c4-9721-a00ffb3c906c.png)
