### ISSUE TITLE
After updating to 3.6.0 required radio field doesn't work

### ISSUE THREAD

**Issue by mavhc** [weDevsOfficial/wp-user-frontend#1325]
If I have a radio field that's set to be required, I cannot submit it, it always returns the page with the field highlighted saying it's required,

**Comment by sapayth** [comment]
Hello @mavhc,
sorry to hear about your problem. As we checked, it seems working on our end. There might be a conflict with another plugin or theme. Let's do a conflict test to be confirmed.

Please deactivate all plugins except the WP User Frontend and WP User Frontend Pro.
Use a default theme such as twenty-twenty.
Clear your site cache as well as the browser cache. Then try again.
If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.
