### ISSUE TITLE
Trying to register with occupied email address: "Loading" instead of error message

### ISSUE THREAD

**Issue by elosha** [weDevsOfficial/wp-user-frontend#1357]
I've created a multi-page form that works pretty well. Errors (missing field, missing terms check, missing CAPTCHA) are displayed correctly. However if I try to register with an occupied email address, **no error is shown** (because the field is on the 1st page?). Instead the submit button is disabled and a loading bar appears, **loading indefinitely**.

**How to reproduce**
1. Create a registration form
2. Make it multi-part, place the field for e-mail address on first page
3. Place CAPTCHA and terms checkbox fields on second page
4. Choose the form as the site's registration form, logout and try to register
5. Enter everything validly, but type in an email address that already is used
6. Observe

**Environment**
- PHP 8.1
- German locale
- Wordpress 6.2.2
- Twenty-Twentytwo theme
- WPUF 3.6.4
- WPUF Pro (Single Site) 3.4.13

**Comment by sapayth** [comment]
Hello @elosha,

sorry to hear about your problem. As we checked, it seems working on our end. There might be a conflict with another plugin or theme. Let's do a conflict test to be confirmed.

Please deactivate all plugins except the WP User Frontend and WP User Frontend Pro.
Use a default theme such as twenty-twenty-three.
Clear your site cache as well as the browser cache. Then try again.

If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.

**Comment by sapayth** [comment]
Considering the issue resolved with our proposed solution. Closing it now. Feel free to reopen if needed.

Appreciate your collaboration!
