### ISSUE TITLE
You can't edit a post while in pending mode.

### ISSUE THREAD

**Issue by moaty** [weDevsOfficial/wp-user-frontend#1370]
Since updating to the latest version - I am now getting this error when I try to moderate a post. Is this a bug you've seen before please? Thanks

<img width="950" alt="image" src="https://github.com/weDevsOfficial/wp-user-frontend/assets/4189764/395ead1e-eedc-4c18-a44e-3c3fe31ccae5">

**Comment by sapayth** [comment]
Hello @moaty,

Sorry to hear about your problem Please update the plugin to the latest version. There is a setting to enable/disable `Pending Post Edit`. You can find it in: **WordPress admin dashboard > WP User Frontend > Settings > Dashboard** section
<img width="1397" alt="image" src="https://github.com/weDevsOfficial/wp-user-frontend/assets/15567340/d9104097-a5d3-407b-bf48-b107b93d67b6">

If you're still getting that problem, please contact the [support](https://wedevs.com/contact) so that we can check it in every possible way.

**Comment by sapayth** [comment]
I hope your problem is solved. If the issue still exist, please feel free to reopen or contact the [support](https://wedevs.com/contact)
