### ISSUE TITLE
When edit a post custom taxonomy data erase.

### ISSUE THREAD

**Issue by kabirbd89** [weDevsOfficial/wp-user-frontend#1377]
I have 1 custom taxonomy along with cat and tag. 

In post form I added custom taxonomy in check box mood and this field is mandatory. In the time of adding post user check custom taxonomy fields and its works good. 
But when user and or admin try to edit the post custom taxonomy checked are cleared. need to select the custom taxonomy fields again. 

I am using the latest version of wp and wpuf.

**Comment by sapayth** [comment]
Hello @kabirbd89,
sorry to hear about your problem. As we checked, it seems working on our end. We can see a custom taxonomy when we edit the post from WordPress dashboard.

Please note, showing taxonomy in the post body depends on the theme. However, if you want to show the taxonomy in the post body, you can follow below solutions. That can break your site if not done correctly. So make a backup before doing anything below:
1. If you are using a block theme, you can change a single post template from `WordPress dashboard > Appearance > Editor > Templates`. 
2. If you are using an older theme, you’ll need to add some code to your WordPress theme or child theme. This code will need to be added to templates files where you want to display the terms. You can manually add this snippet to your theme files, such as single.php, content.php, archive.php, or index.php.
`<?php the_terms( $post->ID, 'custom_taxonomy_slug' ); ?>`


If nothing works, there might be a conflict with another plugin or theme. Let's do a conflict test to be confirmed.

Please deactivate all plugins except the WP User Frontend and WP User Frontend Pro.
Use a default theme such as twenty-twenty-three.
Clear your site cache as well as the browser cache. Then try again.
If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.

**Comment by kabirbd89** [comment]
@sapayth Its not about showing data in post. 

I am telling about post edit screen, I checked again. The problem is still there. Every time user/admin edit there post they need to select tick mark again. 

There is no plugin conflict, problem only happened when setting is, 
Custom Tax Name > Advance Setting > Type > **Checkbox** 

In all other setting there is no problem. i.e 
Custom Tax Name > Advance Setting > Type > Select 
or
Custom Tax Name > Advance Setting > Type > Multiselect all are okey.

**Comment by sapayth** [comment]
Hello @kabirbd89,
Thanks for the clarification. There is indeed a bug there. Please replace `wpuf-functions.php` file with [this](https://raw.githubusercontent.com/weDevsOfficial/wp-user-frontend/932cebaafdba007b41d0edc119125ccfb1bbb403/wpuf-functions.php) and `includes/class-frontend-render-form.php` with [this](https://raw.githubusercontent.com/weDevsOfficial/wp-user-frontend/932cebaafdba007b41d0edc119125ccfb1bbb403/includes/class-frontend-render-form.php) file. Please take a backup of your site before making the changes. Feel free to comment here for any queries

**Comment by kabirbd89** [comment]
@sapayth Thankyou for your fast response, I just update the files and its work as expected.
