### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by swinggraphics** [weDevsOfficial/wp-user-frontend#1378]
The warning is generated on every admin page. I added the backtrace output.

Warning: Array to string conversion in /wp-includes/formatting.php on line 1107
#0 wp_check_invalid_utf8(Array ([slug] => invoices,[label] => Invoices)) called at [/wp-includes/formatting.php:4693] #1 esc_attr(Array ([slug] => invoices,[label] => Invoices)) called at [/wp-content/plugins/wp-user-frontend/wpuf-functions.php:2101] #2 wpuf_get_account_sections_list() called at [/wp-content/plugins/wp-user-frontend/admin/settings-options.php:321] #3 wpuf_settings_fields() called at [/wp-content/plugins/wp-user-frontend/admin/class-admin-settings.php:160] #4 WPUF_Admin_Settings->get_settings_fields() called at [/wp-content/plugins/wp-user-frontend/admin/class-admin-settings.php:71] #5 WPUF_Admin_Settings->admin_init() called at [/wp-includes/class-wp-hook.php:310] #6 WP_Hook->apply_filters(, Array ([0] => )) called at [/wp-includes/class-wp-hook.php:334] #7 WP_Hook->do_action(Array ([0] => )) called at [/wp-includes/plugin.php:517] #8 do_action(admin_init) called at [/wp-admin/admin.php:175] #9 require_once(/wp-admin/admin.php) called at [/wp-admin/plugins.php:10]

**Comment by sapayth** [comment]
Hello @swinggraphics,
sorry to hear about your problem. As we checked, it seems working on our end. There might be a conflict with another plugin or theme. Let's do a conflict test to be confirmed.

Please deactivate all plugins except the WP User Frontend and WP User Frontend Pro.
Use a default theme such as twenty-twenty.
Clear your site cache as well as the browser cache. Then try again.
If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.

**Comment by swinggraphics** [comment]
Yes, this appears on every admin page with only Twenty Twenty-Three, WP User Frontend and WP User Frontend Pro active.

**Comment by sapayth** [comment]
Please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.

**Comment by sapayth** [comment]
Considering the issue resolved with our proposed solution. Closing it now. Feel free to reopen if needed.

Appreciate your collaboration!

**Comment by swinggraphics** [comment]
In case anyone else runs into this, my solution was to stop using WP User Frontend and WP User Frontend Pro.
