### ISSUE TITLE
Publishing or editing a woocommerce product on wordpress backend is not possible when the plugin is active

### ISSUE THREAD

**Issue by mhmdcg** [weDevsOfficial/wp-user-frontend#1382]
Recently I saw that I can't publish a new product or edit an existing product on WordPress dashboard. Only it's possible when I deactivate the WPUF plugin. I also checked the console error message when I press "publish" or "update" button.
This is the error: 

Uncaught TypeError: Cannot read            wpuf-admin.js?ver=3.6.7:140 
properties of null (reading 'getContent')
    at HTMLInputElement.<anonymous> (wpuf-admin.js?ver=3.6.7:140:48)
    at HTMLInputElement.dispatch (jquery.min.js:2:39997)
    at v.handle (jquery.min.js:2:37968)
(anonymous)	@	wpuf-admin.js?ver=3.6.7:140
dispatch	@	jquery.min.js:2
v.handle	@	jquery.min.js:2

**Comment by sapayth** [comment]
Hello @mhmdcg,
Sorry to hear about your problem.
Please replace wp-user-frontend/assets/js/wpuf-admin.js file with [this](https://raw.githubusercontent.com/weDevsOfficial/wp-user-frontend/655b10afb43f9b06ec7be8298e51b08bc12f6bed/assets/js/wpuf-admin.js) file. If the problem still exists, please [contact support](https://wedevs.com/contact/) so that the problem can be inspect more deeply

**Comment by mhmdcg** [comment]
Hi @sapayth 
Thanks for your comment. I tried, but it still exists. I will contact support
