### ISSUE TITLE
Plugin breaks saving posts with no content field

### ISSUE THREAD

**Issue by LariElovainio** [weDevsOfficial/wp-user-frontend#1384]
Say you have a custom post type with no editor. You try to publish a post in the backend. Nothing happens, there’s a javascript error.

**wpuf-admin.js** contains the following line:
`var postContent = tinymce.activeEditor.getContent();`

Saving is interrupted because `tinymce` is `undefined`.

**Comment by sapayth** [comment]
Hello @LariElovainio,

sorry to hear about your problem. Updating the plugin to the latest version might fix the issue. Hopefully, this solution will work for you.

If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.

**Comment by sapayth** [comment]
fixed in the latest release
