### ISSUE TITLE
Conditional logic doesn't support WooCommerce attributes

### ISSUE THREAD

**Issue by mhmdcg** [weDevsOfficial/wp-user-frontend#1399]
Hi, I'm using some of WooCommerce attributes in the post form. So I drag and drop one of the existing attributes from the taxonomies list on the right side. I need some conditional logics for them. But it seems, the conditional logic only supports the custom fields, not WooCommerce attributes, and after choosing "yes" for conditional logic, in the dropdown menu you can't  find your existing field that is a WooCommerce attribute.
Is there any solution?

**Comment by sapayth** [comment]
Hello @mhmdcg 
sorry to hear about your problem. As we checked, it seems working on our end. There might be a conflict with another plugin or theme. Let's do a conflict test to be confirmed.

Please deactivate all plugins except the WP User Frontend and WP User Frontend Pro.
Use a default theme such as twenty-twenty-three.
Clear your site cache as well as the browser cache. Then try again.
If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.

**Comment by mhmdcg** [comment]
Hi @sapayth 
Thanks for your reply, Are you sure it's working for you?
Because I just tried on a brand new wordpress website, without any plugin, just WPUF and Woocommerce. But it's not working!
I also attached a screenshot. I think I need to contact support.
![WPUF-PA](https://github.com/weDevsOfficial/wp-user-frontend/assets/143349636/162e81be-1810-45d2-bf3c-bfd53e4de781)

**Comment by sapayth** [comment]
Please replace `line no: 351` of`wpuf-pro/assets/js/wpuf-form-builder-components-pro.js` with below code:

`field_type: (wpuf_cond.field_type !== undefined) && (wpuf_cond.field_type[i] !== undefined) ? wpuf_cond.field_type[i] : ''`

If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.

**Comment by mhmdcg** [comment]
Thanks @sapayth , I replaced the code, but still is the same... I will contact support. Thanks!

**Comment by sapayth** [comment]
Considering the issue resolved with our proposed solution. Closing it now. Feel free to reopen if needed.

Appreciate your collaboration!
