### ISSUE TITLE
Post Forms Edit Page Blank

### ISSUE THREAD

**Issue by 9demnex** [weDevsOfficial/wp-user-frontend#1407]
When I go to edit one of my existing Post Forms, the page to edit them loads blank. Just a white page. The WP admin bar and left menu are still there.

Also just noticed when I try and create a new form. Blank.

WordPress 6.4.2
PHP 8.2
WP User Frontend 4.0.2
WP User Frontend Pro - professional 4.0.1

**Comment by sapayth** [comment]
hello @9demnex,

Sorry to hear about your problem. Please make sure you are using the latest version of WP User Frontend[v4.0.3] and WPUF pro[v4.0.5]. And what is your site language?

If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.

**Comment by 9demnex** [comment]
Problem persists. Where do I download WPUF pro[v4.0.5]? My site language is English.

**Comment by sapayth** [comment]
Please contact [support](https://wedevs.com/contact) with your license key to download the latest WPUF pro

**Comment by anik-fahmid** [comment]
@Rat01047 vai, please close this issue?

**Comment by Rat01047** [comment]
@anik-fahmid,
Closed as per instructions...
