### ISSUE TITLE
google maps locations

### ISSUE THREAD

**Issue by Pchlorenzo** [weDevsOfficial/wp-user-frontend#1425]
With the latest plugin updates, we can not show the map’s locations.

Example:
[wpuf-meta name="mapa" type="map" height="304" width="100%" zoom="10"]

The page I need help with https://www.rightsupply.net/emas_statement/copcisa/

Thank you in advance.

Pablo.

**Comment by Pchlorenzo** [comment]
Hello, and good morning. ;-)
Could you please tell me whether the next plugin update will fix this issue? When could it be ready for customers?
I really appreciate any help you can provide. Thank you.
Pablo

**Comment by Pchlorenzo** [comment]
At the moment, we have downgraded the core plugin to the WP user frontend to Version 3.6.9 | and the Pro version to Version 3.4.12. 

Then all the maps are showing correctly.

I'm hoping you fix it in the next plugin version.

Many thanks for considering my request.

**Comment by Pchlorenzo** [comment]
Hi. ;-)

The same with the last update Versión 4.0.6. The maps only show the form but not at the frontend with the shortcode.

Thank you.

**Comment by sapayth** [comment]
Hello @Pchlorenzo,

sorry to hear about your problem. As we checked, it seems working on our end. There might be a conflict with another plugin or theme. Let's do a conflict test to be confirmed.

Please deactivate all plugins except the WP User Frontend and WP User Frontend Pro.
Use a default theme such as twenty-twenty-three.
Clear your site cache as well as the browser cache. Then try again.

If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.

**Comment by Pchlorenzo** [comment]
Is not only our problem. It worked fine in previous plugin versions, so its a problem of your updates. Also with the updates in other pages the same. 

We have uninstall plugins and theme. The same.

We are a customer from years. Please, please... fix it. 

Thank you in advance.
Pablo

**Comment by anik-fahmid** [comment]
@Pchlorenzo I hope you already contacted our support. If not please contact support by selecting the pre-sales category.

**Comment by Rat01047** [comment]
@anik-fahmid,
Working fine on my end.
Closing this issue
