### ISSUE TITLE
Curly autogenerated quotation marks in shortcodes [wpuf-meta name="meta_key_name" type="file"]

### ISSUE THREAD

**Issue by Pchlorenzo** [weDevsOfficial/wp-user-frontend#1431]
Good evening to all.

Every time we save a post from the edit backend that contains shortcodes of a kind…

[wpuf-meta name="meta_key_name" type="file"]

The quotation marks automatically change to curly ones and the function shortcode doesn’t work.

Our theme is Avada.

what can we do.? Only happens with that code.

thank you in advance.
Pablo

**Comment by sapayth** [comment]
Hello @Pchlorenzo,

sorry to hear about your problem. As we checked, it seems working on our end. There might be a conflict with another plugin or theme. Let's do a conflict test to be confirmed.

Please deactivate all plugins except the WP User Frontend and WP User Frontend Pro.
Use a default theme such as twenty-twenty-three.
Clear your site cache as well as the browser cache. Then try again.

If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.
