### ISSUE TITLE
Dashboard page only list "post" post type

### ISSUE THREAD

**Issue by CBeghin** [weDevsOfficial/wp-user-frontend#336]
Hi,
Thank for the plugin.

On the Dashboard page, in the listing, only the posts (i mean the post with the "post" post_type) are showed.
Do there is a way to display all post type content ?

**Comment by mahbubme** [comment]
Hello @CBeghin,

If you want to display a specific post type, you need to mention that. For example, if you want list event instead of post, you can use **[wpuf_dashboard post_type="event"]**.

However, it's not possible to show all post type content using a single shortcode, but using **[wpuf_dashboard post_type="your_post_type"]** multiple times by specifying **post_type** value. 

Please check the documentation here: https://wedevs.com/docs/wp-user-frontend-pro/getting-started/user-dashboard/

Thanks

**Comment by CBeghin** [comment]
Thank you for responding quickly, it work perfectly.

I got the same issue on the "Account" page, on the tab "Posts" witch it show only post contents.
I've tried to add post_type parameters on account shortcode: [wpuf_account post_type="directory"], but apparently it does not support params.
Do there is a solution ?

Thanks.

**Comment by mahbubme** [comment]
Hello @CBeghin,

The post_type attribute will not work with wpuf_account shortcode. That shortcode only supports default functionality. You can show directories on a different page using **[wpuf_dashboard post_type="directory"]** shortcode. 

Thanks
