### ISSUE TITLE
Fields with multiple input option should allow saving as array as well.

### ISSUE THREAD

**Issue by rafsuntaskin** [weDevsOfficial/wp-user-frontend#360]
Many a times it is required that we save any kind of MultiSelect or MultiCheckbox data as array instead of a single string value.

**Comment by ironicmoka** [comment]
Hi there @rafsuntaskin, this issue is mentioned in https://wordpress.org/support/topic/multiple-checkboxes-meta-key-issue/ and addressed as feature for future releases.
I installed WP User Frontend Pro few days ago, but I still don't see any option in the form UI.
Also: only meta_key is saved and there's no way to print the array of labels afterwards.

**Comment by rafsuntaskin** [comment]
@ironicmoka I assume all the fields are saved like an array at this moment. But I am not 100% sure as I am not working with the weDevs team anymore.

@thebengalboy Can you please help him out with this?

**Comment by ironicmoka** [comment]
Thank you for your response @rafsuntaskin.

Unfortunately right now checkbox are still saved as string in the database and no option is provided in the backend (or I wasn't able to find out where it is).
Anyone from weDevs can follow up?
