### ISSUE TITLE
Issue with custom fields

### ISSUE THREAD

**Issue by RekunLive** [weDevsOfficial/wp-user-frontend#581]
Hi
I have a post form with a image upload field, which works great releases up to and including 2.9.2.
Version 2.9.3 and 2.9.4 have a bug regarding the custom field.

The image upload field is using a Metadata key called Images, and in posts created with the old version i get an an Metadata entry for each image with an attachment id like in this image
https://imgur.com/a/rvREu3D

However in the new version there seems to be something wrong with the post metadata creation:
https://imgur.com/a/rpwWB4o

This gives me issue with retrieving and displaying the images.

Hope you can help, and thanks in advance

**Comment by kenswift** [comment]
I have somewhat similar issues with the metadata in versions 2.9.3 and 2.9.4. It took me about a day to figure out that it was actually the update from 2.9.2 to a newer version that causes problems. 

From 2.9.3. it is not possible to keep empty custom fields - eg. when I added photo uploads to the post form, but did not actually upload an image, upon saving my post would be populated with a default image icon in the WPUF Custom Fields section (which can be seen when editing the post as an admin) rather than the default empty 'select image'. Also the custom field would not be empty but it would carry a '0'.

**Comment by mahbubme** [comment]
Hello @kenswift & @RekunLive, 

Have you updated WPUF plugin to the latest version (3.0.1)? If the issue still persists after updating the plugin then please contact [here](https://wedevs.com/contact) with your site details. We will be happy to help you.

Thanks
