### ISSUE TITLE
Can't upload images since last update

### ISSUE THREAD

**Issue by IdanGabay** [weDevsOfficial/wp-user-frontend#589]
Hi, last update (with duplicate images) disabled front-end image upload on my site.
when I click the button to choose the desired image, nothing happened.
I saw another post online about this issue that opened 20 hours ago, 
so I assume it is a problem with last update. Thank you !

**Comment by emazharulislam** [comment]
Hello,

When I checked locally, the issue was not there. That's why it's really hard to provide the solution in this way. Most probably, there might have a theme or plugin conflict that causing the problem. Could you please contact [here](https://wedevs.com/contact/) with your site details?

Thanks.

**Comment by IdanGabay** [comment]
OK thank you ! will do
