### ISSUE TITLE
Create Product: no submit button

### ISSUE THREAD

**Issue by reader-man** [weDevsOfficial/wp-user-frontend#639]
I used your plugin:
https://wordpress.org/plugins/wp-user-frontend/
in our website:
https://www.freejshamali.com/

but when i tried to create a product, the submit button did not show at the end of the page:
![wcf](https://user-images.githubusercontent.com/12806275/53901084-175bd880-404f-11e9-88a4-1c0b0b0a667a.png)

**Comment by emazharulislam** [comment]
Hello @reader-man,

There might the theme/plugin conflicts, which caused this issue. Because I checked locally, the issue was not there. If you are facing this issue that means you are facing this especially. If you have done any customization please remove them temporarily and check the scenario again. If you found that the customization didn't occur the issue it is my humble request to you to check the conflict. Here is the [guideline](https://thebengalboy.com/best-practice-find-wordpress-theme-plugin-conflicts/) of checking the conflicts.

Thanks.
