### ISSUE TITLE
Frontend post form works only for admin user

### ISSUE THREAD

**Issue by peterkim0717** [weDevsOfficial/wp-user-frontend#643]
I did not change much of the default setting. I have only admin and contributors.

**Comment by emazharulislam** [comment]
Hello @peterkim0717,

I am very sorry to inform you that, I am not clear about your query. Could you please elaborate your query with a bit more information so that I can be helpful for you? Especially please share a screenshot (You can use https://snag.gy for easily sharing screenshots. You’ll just need to follow the instructions on the page, then paste the URL into this chat window. It works with Chrome, Firefox, and IE.) of what you are facing/trying to achieve?

Thanks.

**Comment by emazharulislam** [comment]
Hello @peterkim0717,

First of all, sorry for the inconvenience. I checked locally the issue was not there. If you are facing this issue that means you are facing this especially. That’s why its really hard to provide the solution in a single word without checking your website.  Would you mind contact our [support center](https://wedevs.com/contact/) with the login credentials so that we can take a closer look? 

Thanks.
