### ISSUE TITLE
Max file size in Image uploader

### ISSUE THREAD

**Issue by mrvinceo** [weDevsOfficial/wp-user-frontend#654]
Hi,

The Insert Photo feature contained in the Post Body field seems to be limited to just 2mb - the Featured Image upload field (and the separate Image Upload field) has an option to increase that limit, which works, but the same option isn't available for the Body Text Insert Photo uploader. Files of up to 50mb (that I've tested so far)  upload fine through the usual post editor; we have a php file max upload limit of 250mb. 

I've found an old reference to this same issue in the WP support area, and that user was directed to alter the max_file_size setting in wp-user-frontend/assets/js/frontend-form.js to something higher than 2mb, but that seems to have no effect. Can the option please be added for Insert Photo, as for the Featured Image field, or can someone please direct me to the relevant file that will affect this change?

Many thanks for an excellent plugin!

**Comment by mahbubme** [comment]
Hello @mrvinceo,

Your site may load min file, if so then you have to change the ### max_file_size limit in frontend-form.min.js file. 

Please check and let me know.

Thanks

**Comment by rob1998** [comment]
I've used this solution as well, but am not fully satisfied, since the file gets overwritten if the plugin gets updated. I would really like to see this getting added in as a setting for the form. At first I thought the only one, but seeing this, I know there are more like me. And probably lots more who don't bother to ask and just accept it.

Please add it 😊
