### ISSUE TITLE
Post Forms - "Campaign End Date" does not have date format option

### ISSUE THREAD

**Issue by traviswarrenhiggins** [weDevsOfficial/wp-user-frontend#776]
The "Campaign End Date" does not properly show a date selection field in the form - only the "insert date / time" Field shows this. 

**Describe the bug:**
If you insert any campaign end date - the only options are "text input" "checkbox" etc. 

**How to Reproduce:**
Log in to your site wp-admin panel. Visit user frontend -> post form & edit your form then insert a campaign end date field on your builder.

**Expected behavior:**

The campaign end date should have the date format and not text input format. 

Additional input (Screenshot/video): https://drive.google.com/open?id=1GFFGQAB7uMKiEfr5Ltz8YMcE4FlLpvqZ

**Comment by ediamin** [comment]
Hello @traviswarrenhiggins we need more details to solve your issue(may need your site admin panel access). Please create a ticket on our site https://wedevs.com/account/tickets/  and we'll follow you there. Thank you very much.

**Comment by itowhid06** [comment]
Hello @traviswarrenhiggins, 

What I can understand from the attached video is, Campaign End Date is a custom taxonomy and not a date field. Therefore you are not getting any date field option. I am closing the issue here as it is really not an issue of WP User Frontend. If you are still facing a problem feel free to open a ticket [Here](https://wedevs.com/account/tickets/). Thanks for your understanding.
