### ISSUE TITLE
My Blog Post Form no longer accepts multiple category fields

### ISSUE THREAD

**Issue by bryanewomack** [weDevsOfficial/wp-user-frontend#831]
RE: WP User Frontend Pro Plugin - I have set up blog post forms on several websites with several category fields on each form to allow search for the blog post under several categories not just one category. But now only one of those category fields is working on each form. I tried creating a new blog post form today and I am only able to have one category field on this new form. Something changed because in the recent past I was able to add more than one category field to a form. Was there a WP User Front End Plugin update that changed this?

**Comment by itowhid06** [comment]
Hello @bryanewomack, Sorry for the inconvenience caused. Actually it was a bug from our end which allowed multiple category field in a form. It was breaking other core features, That's why we had to fix it. Now you can have only one category field in a form. But you can select "multiselect" or "checkbox" to select multiple category in a post according to the attached image.
![image](https://user-images.githubusercontent.com/12055657/77502384-f1d18500-6e84-11ea-92e5-0c078d8f8632.png)

Thank you for your understanding.

**Comment by bryanewomack** [comment]
MultiSelect does NOT let me select multiple categories.  What are the other parameters of that field supposed to be? In the MultiSelect Box I can only highlight one item.  The Checkbox choice does let me select multiple categories but all of the choices are listed on the page instead of in a dropdown box.

**Comment by bryanewomack** [comment]
I was able to use the checkbox option to solve my problem.  I am able to select multiple category choices on the front end using the checkbox and I decided that I like having all of the category choices presented as a long list. So all is good!!!
