### ISSUE TITLE
New feature added - Automatically cancel Subscription when custom post count is zero

### ISSUE THREAD

**Issue by bazzar701** [weDevsOfficial/wp-user-frontend#832]
Hello,

We needed a feature for our project to automatically end a subscription (cancel) when there were no more custom posts available for the user.
We hired a developer for this purpose and he made our custom code. We decided to share for other users that need the same feature. It is saved in functions.php so it is not deleted with WPUF updates:

You only need to change "custom_post_type_name" to your custom post type name.

> add_filter( 'wpuf_add_post_after_insert', function () {
> $current_user = wpuf_get_user();
> $current_pack = $current_user->subscription()->current_pack();
> 
> // $form_settings['post_type']
> $has_post_count = $current_user->subscription()->has_post_count( 'custom_post_type_name' );
> 
> // the current plan is active, but there are no posts left
> if ( ! is_wp_error( $current_pack ) && ! $has_post_count ) {
> // deleting plan from the user
> $current_user->subscription()->delete_pack();
> }
> } );

**Comment by shabnam611** [comment]
Hello @bazzar701,

thank you for your input. We will check the feature and will take the required step. 

Regards,

**Comment by zamandevs** [comment]
@bazzar701 What you've done is the right way. it doesn't make sense in the subscription option due to some caveats ( rollback, expiration etc. ) and against generic behavior. what you're doing above is basically pay per post scenario cause you're selling post count. subs primarily for period management. so please think about this.
