### ISSUE TITLE
File slug naming issue for the same file type

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#853]
**How to reproduce the issue**:

- Create a form with a feature image field.
- Now upload a file/image with (like Image1.jpg) then submit post or press delete icon to remove and upload another image with the same name (like Image1.jpg). Make sure the second image is not the same just upload another with the same naming.
- Then you will notice the second image is uploaded instead of the system converted the image into the first one. At the same time, the second image is not passed into the WP backend Media.

**Additional Screencast:** Please [check this video](https://drive.google.com/file/d/1ZwTvW01CjFZsaVo5ru1VUvqZZ139T579/view?usp=sharing).

**Expected Behaviour**: It should rename the same file(name) according to WordPress core system by appending the file [slug name like Image1-1.jpg](http://prntscr.com/ryo66d).

**Comment by konsumkunst** [comment]
This also happens without saving the form. Once the image is uploaded its already saved. So the delete-function is only an "optical illusion".

**Comment by ediamin** [comment]
- This issue raises after adding a fix for the issue #809. 
- This fix not perfect yet. Now WPUF will check for both **file name** and **file size** to prevent duplicate image upload. If you have two different images but their file name and size are both same, then there will be only one upload.
- Deleting image was fixed in dd0e513ca1c77810f3e4ef53364f4cbc89729029
