### ISSUE TITLE
Redirect After Login no longer working after latest update.

### ISSUE THREAD

**Issue by markob17** [weDevsOfficial/wp-user-frontend#887]
The latest update broke this. On Firefox, Chrome, and Opera, it doesn't redirect. On Microsoft Edge, it doesn't redirect either but it also does not load any page (blank) unless you do browser refresh.

**Comment by ediamin** [comment]
@markob17 Thanks for reporting the issue. Yes, indeed there is a bug in latest update. But it could be different for different settings and I need to know what settings you're using. Would you please post a screenshot of your `Login/Registration` settings in WP User Frontend > Settings page?

**Comment by markob17** [comment]
> 
> 
> @markob17 Thanks for reporting the issue. Yes, indeed there is a bug in latest update. But it could be different for different settings and I need to know what settings you're using. Would you please post a screenshot of your `Login/Registration` settings in WP User Frontend > Settings page?

Please see the attached screenshot. 

<img width="594" alt="Capture" src="https://user-images.githubusercontent.com/6548629/84475228-606cf480-acb6-11ea-83eb-4d12146704b0.PNG">

**Comment by markob17** [comment]
NOTE: I am redirecting to the page that includes the [wpuf_dashboard] shortcode.

**Comment by ediamin** [comment]
@markob17 Thanks for the screenshot. I've pushed a commit with fix. Please download the Github develop branch and test if your problem is fixed or not. I'll update the wp.org plugin repo once I got confirmation from you.

You can download the develop branch zip with "Download Zip" button
<img width="514" alt="Screenshot 2020-06-12 at 4 15 37 PM" src="https://user-images.githubusercontent.com/1541774/84492738-784d7400-acc8-11ea-87fe-e2ec0fc150f8.png">

**Comment by markob17** [comment]
@ediamin Hello, sir. I just tested this out and the issue with login redirect now seems to be resolved.

Cheers,

Mark

**Comment by Fendt1** [comment]
thank you for the fast answer.

How to apply the patch?
i am not a programmer.

**Comment by ediamin** [comment]
@Fendt1 click this link https://github.com/weDevsOfficial/wp-user-frontend/archive/develop.zip, you'll get the plugin zip file. Delete the current plugin in your WordPress site and upload the zip there.

**Comment by Fendt1** [comment]
Dear ediamin,

I downloaded the new develop files and deleted the last pro file.
But it is the same. I cannot login to the admin area.

**Comment by Fendt1** [comment]
I installed the files from new, and i cannot come into the admin area with wp-admin BUT with 
wp-login. 

So, this is a hack somehow. I hope you can solve this in the future, as the real solution is to go in with wp-admin.

Thank you for the zip-files.

**Comment by ediamin** [comment]
@Fendt1 If you have no problem granting access to your site, please contact support at our wedevs.com site. I'll try to figure out the issue by logging into your site.

**Comment by lmoncany** [comment]
Same issue here since the update.

had to uncheck the option "override wordpress default login" in order to get it working. and avoid 2 clients website being blocked.

**Comment by Fendt1** [comment]
Since 3.3.1 i cannot login.

If i go to WP-ADMIN: i am rederected to account in frontend.
If i go to WP-LOGIN: i am rederected to account in frontend.

But if i log-in with the login-widget in the sidebar, i come in to the frontend and can see the black bar on top of the ADMIN-Area. and then i can come into the ADMIN.

So this is a trick17.

**Comment by Fendt1** [comment]
Sorry.  It does not work.
Also if i see the black Admin-bar i can NOT come into the ADMIN!

Always rederected to frontend dashboard.
