### ISSUE TITLE
Bug: Edit User by Admin in backend Sets Unlimited to 1970

### ISSUE THREAD

**Issue by mappersacademy** [weDevsOfficial/wp-user-frontend#891]
Hi,
This bug predates the recent update last Thursday.

Every time an Admin edits a user profile in the WP dashboard, the free unlimited WPUF subscription that was allocated goes to an expired date 1970. We then have to remove the subscription and allocate the package fresh and all is okay.

Not an urgent issue, but obviously annoying.

**Comment by Fendt1** [comment]
This problem was also before this update to 3.3.0.

What is the solution?

As for members it is a strange situation, as they get a mail, that their
subscription is terminated. And for the admin it is unwanted traffic.

Best

Josef

Am So., 14. Juni 2020 um 09:08 Uhr schrieb mappersacademy <
notifications@github.com>:

**Comment by zamandevs** [comment]
@mappersacademy Fixed. will be on the coming release.
