### ISSUE TITLE
Editors are nog able to work with wordpress anymore,  (this happens when i activate the plugin)

### ISSUE THREAD

**Issue by hettys** [weDevsOfficial/wp-user-frontend#979]
Hello,
I have been using wp user frontend for almost 2 years now. It always worked fine. But since the last update is doesn’t work good any more.
I tried to roll back to an older version. This succeeded but the problem was still there. I tried several versions but nothing would helped the problem.

See the post of tholub (@tholub) which described the problem.
I know that this problem is send to the githubb.

My question…
Does the pro version has the same problems? I really want this problem to be solved and im willing to pay for it

**Comment by mmarj** [comment]
Hello @hettys 

I am assuming you are also facing[ this issue](https://github.com/weDevsOfficial/wp-user-frontend/issues/972) with your Editor users. If yes, then please be informed that this issue is fixed already (checked the comments on the issue). So you can also try by download and install the current [developed version](https://github.com/weDevsOfficial/wp-user-frontend/archive/develop.zip). I hope this will helps.

Best regards.

**Comment by hettys** [comment]
Hello,
I installed the version, but it is still not working
It has something to do with the user roles.
I am the admin and i dont have problems. But the authors have the problem.
When i activate the plugin  wp user frontend they dont have acces anymore
to  the site. By loggin in they are redirecting  at the frontend of the
site.

When i create an subscriber at the backend and im login in with this
subscriber, he can work at the backend???
I dont understand it


Op ma 21 sep. 2020 om 21:50 schreef MM Aurangajeb <notifications@github.com
